### ISSUE TITLE
Using Method 

### ISSUE THREAD

**Issue by zgramming** [Ephenodrom/Dart-Basic-Utils#1]
i'm using method like this, 

`Future<Map<String, dynamic>> deleteForJson(String url,
      {Map<String, String> queryParameters,
      Map<String, String> headers}) async {
Map<String, dynamic> response = await HttpUtils.deleteForJson(url,
        queryParameters: queryParameters, headers: headers);
    Map responseJson = json.decode(response);
    print(responseJson);
    return responseJson;
}`
But I'm getting error 
`The argument type 'Map<String, dynamic>' can't be assigned to the parameter type 'String'.`
Something mistake ?

**Comment by Ephenodrom** [comment]
Hello,

On which line do you get the error ?
For me it looks like your API does not return a proper json.

Try something like this and check the output :


```dart
Future<Map<String, dynamic>> deleteForJson(String url, {Map<String, String> queryParameters, Map<String, String> headers}) async { 
    var response = await HttpUtils.deleteForResponse(url, queryParameters: queryParameters, headers: headers); 
    print(response.body); // Check the output, if it is in json format
    return json.decode(response.body);
}
```

# Additional Information :

You can shorten your method that you posted, you don't need to call json.decode();

```dart
Future<Map<String, dynamic>> deleteForJson(String url, {Map<String, String> queryParameters, Map<String, String> headers}) async { 
    Map<String, dynamic> response = await HttpUtils.deleteForJson(url, queryParameters: queryParameters, headers: headers); 
    print(response); 
    return response; 
}
```

**Comment by zgramming** [comment]
Hello thank's for reply,  i try your code like this :
`Future<Map<String, dynamic>> deleteForJson(String url, {Map<String, String> queryParameters, Map<String, String> headers}) async { 
    Map<String, dynamic> response = await HttpUtils.deleteForJson(url, queryParameters: queryParameters, headers: headers); 
    print(response); 
    return response; 
}`
But Getting Error : Exception has occurred.HttpResponseException (Response error ...)

It's My View : 
`void _deleteD(String id) async{
    var result = await api.deleteForJson('${Urls.BASE_API_URL}/mahasiswa/delete/id/$id',headers:{"Content-type":"application/json"} );
    if(result != null){
      _showSnackBar(context, 'Hapus ${widget.nama} Berhasil');
    }else{
      _showSnackBar(context, 'Hapus ${widget.nama} gagal');
    }
  }`

**Comment by Ephenodrom** [comment]
The exception only occures, if the status code received in the response is greater than 299. That means that your API delivers an error.

try this : 

Update to the latest version 1.6.0 and change the code like this.

```dart
Future<Map<String, dynamic>> deleteForJson(String url, {Map<String, String> queryParameters, Map<String, String> headers}) async { 
    try{
        Map<String, dynamic> response = await HttpUtils.deleteForJson(url, queryParameters: 
              queryParameters, headers: headers); 
   }catch(HttpResponseException e){
        print(e.statusCode);
        print(e.body);
        print(e.headers);
    }
    print(response); 
    return response; 
}
```

Check the output for the status code.

**Comment by zgramming** [comment]
I'm already try delete data using POSTMAN and this work but must have **body** , but delete function in dart dont have **Body** for delete it, only have **Header**. How can i fix this ?
<img width="960" alt="2019-08-08 (1)" src="https://user-images.githubusercontent.com/38829404/62717155-935ab200-ba2d-11e9-9f7b-14a01715fefe.png">

**Comment by Ephenodrom** [comment]
Ah ok now it makes sense.
But you have to change your API. 

As mentioned in this RFC(https://tools.ietf.org/html/rfc7231#section-4.3.5) , a DELETE request should not have a body. 

>A payload within a DELETE request >message has no defined semantics; >sending a payload body on a DELETE >request might cause some existing >implementations to reject the request.

Two solutions :
1) Change your API to accept a POST request for this route and use the postForJson method of the HttpUtils.
2) Change your API to use the ID passed in the url to delete the entity.

Additional Information :
Check out my other flutter / dart packages like my framework EZ Flutter at <https://github.com/Ephenodrom/EZ-Flutter>

Regards

**Comment by zgramming** [comment]
Can you tell me how to implement solution you give? I'm stuck in this delete operation .
So for deleting data i must use post instead of delete or what?
Thank's.

**Comment by Ephenodrom** [comment]
Change your API so the Request **DELETE http://192.168.43.159/wpu-rest-server/apii/mahasiswa/delete/101** will trigger your delete function in the API.

The function has to grab the ID from the url and process the delete with the ID. You can test this within postman. I don't know your API, so I can't tell you how to change your API.

After that is done, you can use HttpUtils.deleteForJson() method to make the DELETE request.
