### ISSUE TITLE
Add cert sha256Thumbprint support

### ISSUE THREAD

**Issue by certaintls** [Ephenodrom/Dart-Basic-Utils#13]
We have sha256Thumbprint support on SPKI field in #12 , but we don't have sha256Thumbprint on the whole cert. Browsers use sha256Thumbprint of the whole cert, e.g. Apple lists the sha256 fingerprints here https://support.apple.com/en-us/HT210770

On the other hand, I see sha1Thumbprint is available on the whole cert, but the format isn't same as browser display, see screenshot below:

![image](https://user-images.githubusercontent.com/59906029/76146747-6f994080-60d0-11ea-94df-7dfa0ea8150f.png)

It seems the space characters was stripped out in `X509CertificateData.sha1Thumbprint`

**Comment by certaintls** [comment]
But, Microsoft doesn't use spaces in fingerprint https://ccadb-public.secure.force.com/microsoft/IncludedCACertificateReportForMSFT hmmm...

**Comment by Ephenodrom** [comment]
Hello @certaintls 
The spaces are only for readability and have no other effect. I added the sha256 thumbprint to the X509CertificateData model.

If you want to to display the thumbprint with spaces you can use the StringUtils :

```dart
var thumbprint =  '1F6254CEDA7E9E9AEBF8B687BDFB5CC03AD1B3E7';
var moreReadable = StringUtils.addCharAtPosition(thumbprint, ' ', 2, repeat: true);
print(moreReadable); // 1F 62 54 CE DA 7E 9E 9A EB F8 B6 87 BD FB 5C C0 3A D1 B3 E7
```

Please update to version 2.5.3 and confirm if this issue is fixed :).

Regards

**Comment by Ephenodrom** [comment]
No response so far. Will close the issue.

**Comment by certaintls** [comment]
Just had a chance to verify; it is working. Thanks again!
