### ISSUE TITLE
Support EC CSR

### ISSUE THREAD

**Issue by kismet-** [Ephenodrom/Dart-Basic-Utils#15]
Currently only RSA CSR generation is supported. RSA is deprecated for CSR. How can we add support for EC csr??

**Comment by Ephenodrom** [comment]
Hello and thanks for the feature request. I will try to add the functionality to generate ECC CSR with the X509Utils class.

**Comment by Ephenodrom** [comment]
- Converting a ECPublicKey to PEM String
- Convertimg a ECPrivateKey to PEM String
- Generating EC CSR as PEM String

**Comment by Ephenodrom** [comment]
@kismet- 
Please update to 2.5.5 and use the following methods :

```dart
AsymmetricKeyPair generateEcKeyPair();
String encodeEcPublicKeyToPem(ECPublicKey publicKey);
String encodeEcPrivateKeyToPem(ECPrivateKey ecPrivateKey);
String generateEccCsrPem(Map<String, String> attributes, ECPrivateKey privateKey, ECPublicKey publicKey);
```
