### ISSUE TITLE
Capitalize each word

### ISSUE THREAD

**Issue by FickleLife** [Ephenodrom/Dart-Basic-Utils#17]
Thanks for the useful plugin!

Browsing the docs, I can see `capitalize` that does `the quick lazy fox -> The quick lazy fox`, but is there a function that does `the quick lazy fox -> The Quick Lazy Fox` ?

**Comment by Ephenodrom** [comment]
Please update to version 2.5.6.

I improved the capitalize method and added the **allWords** parameter. If you set this to **true** it will capitalize all words of a string. See the description of the method for more information and take a look at this example :

```dart
String capitalized = StringUtils.capitalize('the quick lazy fox', allWords: true);
```

Feel free to suggest more features!
