### ISSUE TITLE
Is February missing?

### ISSUE THREAD

**Issue by awhitford** [Ephenodrom/Dart-Basic-Utils#26]
https://github.com/Ephenodrom/Dart-Basic-Utils/blob/3b53270fc71b9d94386a0a5d7240c4a59b80665e/lib/src/DateUtils.dart#L133-L139

Is February missing?

**Comment by awhitford** [comment]
Also, these _if_ statements are mutually exclusive, so an _else if_ is more appropriate.

**Comment by Ephenodrom** [comment]
@awhitford 
Thanks again for the PR :).
