### ISSUE TITLE
Add php strtotime equivalent 

### ISSUE THREAD

**Issue by Ephenodrom** [Ephenodrom/Dart-Basic-Utils#3]
Add strtotime equivalent that supports the following kind of strings:
* now :heavy_check_mark:
* yesterday :heavy_check_mark:
* tomorrow :heavy_check_mark:
* +1 year 2 months 3 weeks :heavy_check_mark:
* -1 year 2 months 3 weeks :heavy_check_mark:
* 2 weeks ago :heavy_check_mark:
* last friday :heavy_check_mark:
* next friday / at 2 pm / 14:00:00 / hours 14 :heavy_check_mark:
* 10 December 2018 :heavy_check_mark: 
* 2 pm / am / next friday :heavy_check_mark: 
* 04.37 pm / am / next day :heavy_check_mark: 
* 9:05:42 pm / am / next day :heavy_check_mark:

**Comment by krista-koivisto** [comment]
I'm really looking forward to this one. It will be really useful for parsing user-entered strings (particularly from voice recognition.) One more suggestion I would have if and when you have time is handling of am/pm strings.

2 pm ( = 14:00:00 today)
04.37 pm ( = 16:37:00 today)
9:05:42 am ( = 09:05:42 today)

And also a combination of time and date like that. Like "2 pm next Monday" for example. Maybe by using a RegExp like `^(([0-9]?[0-9][:.\s]?){1,2}[0-9]?[0-9]?\s*(am|pm)?)\s+([\w\s]+)$` to split the time and date and then parsing each of them again?

**Comment by Ephenodrom** [comment]
Added DateUtils and unit tests with version 1.9.0. Version is already available via pub.dev. Will update the method to allow more strings in the future.

   Supported strings at the moment:
   * now
   * + 1 year|y 2 month|m 3 weeks|w 4 hours|h 5 minutes|m 6 seconds|s
   * - 1 year|y 2 month|m 3 weeks|w 4 hours|h 5 minutes|m 6 seconds|s
   * yesterday (at 1 pm|1 hour|13:00:00)
   * tomorrow (at 1 pm|1 hour|13:00:00)
   * last monday (at 1 pm|1 hour|13:00:00)
   * next monday (at 1 pm|1 hour|13:00:00)
   * 10 September 2019 (at 1 pm|1 hour|13:00:00)
   * 1 day(s)|week(s)|month(s) ago
   * 2 pm next monday|week
