### ISSUE TITLE
Upgrade dependency to json_annotation

### ISSUE THREAD

**Issue by slavap** [Ephenodrom/Dart-Basic-Utils#32]
Because basic_utils 2.6.3 depends on json_annotation >=2.0.0 <=3.0.1 and no versions of basic_utils match >2.6.3 <3.0.0, basic_utils ^2.6.3 requires json_annotation >=2.0.0 <=3.0.1.

Current version of json_annotation is 3.1.0

**Comment by Ephenodrom** [comment]
@slavap I updated json_annotation and json_serializable to the latest version on pub.dev. This will be shipped with the next release on pub.dev.

Regards
