### ISSUE TITLE
Add null safety support

### ISSUE THREAD

**Issue by enyo** [Ephenodrom/Dart-Basic-Utils#34]
Since a few packages depend on this package, it would be great if this could be adopted to null safety.

**Comment by Ephenodrom** [comment]
Hello and thank you for the issue. Null Safety is on the roadmap but I have to wait for all other packages that I use to update. If this is done, I will check out Null Safety and try to implement it.

But this will still take some time!

**Comment by enyo** [comment]
Thanks!

I think that actually all your dependencies are already migrated. For `pointycastle` there is a PR that you can use: https://github.com/bcgit/pc-dart/pull/77

The reason they didn't release it, is that they might do some improvement to the API, but in general you can use it as a starting point.

All other libraries are already released as `nullsafety-*`.

**Comment by Ephenodrom** [comment]
I will keep this issue updated, when i make some progress in migrating to null safetey. 
Regards

**Comment by AKushWarrior** [comment]
The PR is actually done and ready for release with all tests passing; that will be the exact version that is published, I believe. So it should be fine for you to temporarily add that as a git dependency in pubspec.yaml (and then change it later when the official version comes out).

**Comment by Anas35** [comment]
Hello, @Ephenodrom  I would happy to make a PR for null safety if there is no WIP. All the packages including `pointycastle` which this project depends have the null-safety version.

**Comment by Ephenodrom** [comment]
@Anas35 Feel free to take over this part, as i am currently really busy. I had no time so far to take a deeper look into null safety.

Please create a PR and i will check it out. When everything is done, i will update the package on pub.dev immediately

**Comment by Ephenodrom** [comment]
@enyo @Anas35 
The preview version **3.0.0-nullsafety.0** is now available via pub.dev. Please try it out and give some feedback.
https://pub.dev/packages/basic_utils/versions/3.0.0-nullsafety.0

All thanks go to @Anas35 for the PR to enable null safety!

**Comment by Ephenodrom** [comment]
@enyo @Anas35 
Any problems so far using the null safety version ?

**Comment by Ephenodrom** [comment]
Published stable version 3.0.0 on pub.dev.
