### ISSUE TITLE
Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.

### ISSUE THREAD

**Issue by MedwinCorreo** [Ephenodrom/Dart-Basic-Utils#37]
![image](https://user-images.githubusercontent.com/16618565/110075888-83988080-7dbe-11eb-8cfd-5bb9e3dc0448.png)

/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/basic_utils-2.7.1/lib/src/HttpUtils.dart:24:37: Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
 - 'Uri' is from 'dart:core'.
    var response = await client.get(finalUrl, headers: headers);        
                                    ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/basic_utils-2.7.1/lib/src/HttpUtils.dart:81:38: Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
 - 'Uri' is from 'dart:core'.
    var response = await client.post(finalUrl, body: body, headers: headers);
                                     ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/basic_utils-2.7.1/lib/src/HttpUtils.dart:144:37: Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
 - 'Uri' is from 'dart:core'.
    var response = await client.put(finalUrl, body: body, headers: headers);
                                    ^
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/basic_utils-2.7.1/lib/src/HttpUtils.dart:203:40: Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
 - 'Uri' is from 'dart:core'.
    var response = await client.delete(finalUrl, headers: headers);     
    
    error after flutter run
    to fix parse finalUrl to Uri

**Comment by Ephenodrom** [comment]
Already fixed with the latest version.
