### ISSUE TITLE
ECDSA Sign/Verifier

### ISSUE THREAD

**Issue by azim92** [Ephenodrom/Dart-Basic-Utils#39]
Hi, was testing out your library since one of it's dependency is [PointyCastle](https://pub.dev/packages/pointycastle). 
Just would like to know if there is an ECDSA Sign/Verifier included in your [CryptoUtils](https://github.com/Ephenodrom/Dart-Basic-Utils/blob/master/lib/src/CryptoUtils.dart), or in another dart file?

**Comment by Ephenodrom** [comment]
@azim92 
As far as i remember, the ECDSA Signing was not yet available when implementing the CryptoUtils. I will take a look on the current stage of the Pointycastle project and check if this is still true or not.

**Comment by azim92** [comment]
@Ephenodrom 

Thank you for your response. If you don't mind, could you have a look at my ECDSA verify/signer with SHA256?
I'm not a knowledgeable individual for crypto related, so would like to inquire for ECDSA signer, which one is the standardize for generating an ECDSA signature? A Probabilistic Signature (Non-Static Signature) or Deterministic Signature (Static Signature)?

Static here indicates the same output or not.

``` dart
  import 'dart:convert';
  import 'dart:math';
  import 'dart:typed_data';

  import 'package:basic_utils/basic_utils.dart';
  import 'package:pointycastle/api.dart';
  import 'package:pointycastle/asn1.dart';
  import 'package:pointycastle/ecc/api.dart';
  import 'package:pointycastle/export.dart';
  import 'package:pointycastle/src/utils.dart' as pcUtils;
  import 'package:asn1lib/asn1lib.dart' as Asnb;

  static Uint8List ecSign(ECPrivateKey privateKey, Uint8List plainDataByte) {
    var signer = Signer('SHA-256/ECDSA');
    var privateParams = PrivateKeyParameter<ECPrivateKey>(privateKey);

    // probabilistic signature
    var secureRandom = FortunaRandom();
    var random = Random.secure();
    var seeds = List<int>.generate(32, (_) => random.nextInt(255));
    secureRandom.seed(KeyParameter(Uint8List.fromList(seeds)));
    var signatureParams = ParametersWithRandom(privateParams, secureRandom);
    signer.init(true, signatureParams);

    return _ecdsaSignatureToASN1Byte(signer.generateSignature(plainDataByte));

    // deterministic signature
    // var signer = ECDSASigner(SHA256Digest(), HMac(SHA256Digest(), 64));
    // signer.init(true, PrivateKeyParameter<ECPrivateKey>(privateKey));
    //
    // return signer.generateSignature(plainDataByte) as ECSignature;
  }

   static bool ecVerify(
      ECPublicKey publicKey, Uint8List plainDataByte, Uint8List signature) {
    // final signature = ECSignature(r, s);
    final verifier = ECDSASigner(SHA256Digest(), HMac(SHA256Digest(), 64));
    verifier.init(false, PublicKeyParameter<ECPublicKey>(publicKey));
    return verifier.verifySignature(
        plainDataByte, _ecdsaSignatureFromASN1Byte(signature));
  }

  static Uint8List ecdsaSignatureToASN1Byte(ECSignature signature) {
    var algorithmSeq = new Asnb.ASN1Sequence();
    var r = new Asnb.ASN1Integer(signature.r);
    var s = new Asnb.ASN1Integer(signature.s);
    algorithmSeq.add(r);
    algorithmSeq.add(s);

    return algorithmSeq.encodedBytes;
  }

  static ECSignature ecdsaSignatureFromASN1Byte(Uint8List signatureByte) {
    var parser = ASN1Parser(signatureByte);
    var object = parser.nextObject() as ASN1Sequence;
    var r = pcUtils.decodeBigInt(object.elements.elementAt(0).valueBytes);
    var s = pcUtils.decodeBigInt(object.elements.elementAt(1).valueBytes);
    return ECSignature(r, s);
  }
```

for `ecdsaSignatureToASN1Byte(...)` function, I had to use ASN1 from `asn1lib: ^0.8.1` package as 
the one provided in `pointycastle: ^2.0.1` gives me an empty ASN1Sequence after adding ASN1Integer to it:

``` 
var algorithmSeq = new Asnb.ASN1Sequence();
var r = new Asnb.ASN1Integer(signature.r);
var s = new Asnb.ASN1Integer(signature.s);
algorithmSeq.add(r);
algorithmSeq.add(s);
```

**Comment by Ephenodrom** [comment]
@azim92 
Please upgrade to version 3.0.0 and you will find two new methods for EC Sign and EC Verify. Please try it out and give some feedback.

PS: The documented list of supported algorithm is not complete, I will have to check again which algorithm are supported and update the list with the next release.

**Comment by azim92** [comment]
Result of my testing:
![image](https://user-images.githubusercontent.com/30527495/114009496-c655e880-9895-11eb-8360-be9f1fc73ffd.png)

Not too sure what happens with SHA-3/ECDSA and SHA-3/DET-ECDSA.

Your EC Sign will support only probabilistic signature I assume?

**Comment by Ephenodrom** [comment]
This seems to be more a problem of "Pointycastle". It seems the package does not support SHA-3/ECDSA and SHA-3/DET-ECDSA. 

I would recommend to open an issue here : https://github.com/bcgit/pc-dart

Then this is possible I just have to update the pointycastle version.

**Comment by Ephenodrom** [comment]
The code documentation has now all working algorithm documented.
