### ISSUE TITLE
Fails to build for web

### ISSUE THREAD

**Issue by gbloggs** [Ephenodrom/Dart-Basic-Utils#46]
The pointycastle dependency

pointycastle: ^3.1.3 

is causing the build for web to fail.

see:

https://github.com/bcgit/pc-dart/issues/112

Please either revert to 3.1.1 or update to 3.2.0 once it is released. 

***UPDATE***

As a work around, I found pointycastle 3.1.2 compiled to web, so pegging the version in the pubspec worked:
```
  basic_utils: 3.3.2
  pointycastle: 3.1.2
```

**Comment by Ephenodrom** [comment]
Hello @gbloggs 

I would recommend to go back to basic_utils: 3.3.2 as this version use pointycastle: ^3.1.2 

I will update this package as soon as the new pointycastle version is available.

**Comment by Ephenodrom** [comment]
@gbloggs Should be fixed now. A new version 3.4.0 is now available on pub.dev including the latest pointycastle release.
