### ISSUE TITLE
CryptoUtils.rsaPrivateKeyExponentToBytes missing ?

### ISSUE THREAD

**Issue by acorn371** [Ephenodrom/Dart-Basic-Utils#49]
Hi,
I need to store a private-key as a byte array (modulus and exponent).
I can save modulus by `CryptoUtils.rsaPrivateKeyModulusToBytes `but no `CryptoUtils.rsaPrivateKeyExponentToBytes `is found.

Is `CryptoUtils.rsaPrivateKeyExponentToBytes`  missing ? And the ....FromBytes related functions ?
How can I save private-key exponent along with private-key modulus to have the whole key stored and then, reloaded ?

Thanks,
Marco

**Comment by Ephenodrom** [comment]
Hello and thank you for the issue. Yes it is correct that the method is missing.

There are 3 ways for your now:
- Save the key as PEM.
- Implent the method in your own and create a PR.
- Wait till i got some time to do it.

I would suggest number one!

Regards

**Comment by Ephenodrom** [comment]
Should bei now available in pub.dev as version 3.6.0.

**Comment by acorn371** [comment]
Thanks,
I'm going to follow Your suggestion!

Marco
