### ISSUE TITLE
isDigit exception on empty string

### ISSUE THREAD

**Issue by modulovalue** [Ephenodrom/Dart-Basic-Utils#5]
Hey :)

Thanks for the great package! 

I found a tiny bug
```dart
 ///
  /// Checks if the given string [s] is a digit
  ///
  static bool isDigit(String s) {
    if (s.length > 1) {
      for (int r in s.runes) {
        if (r ^ 0x30 > 9) {
          return false;
        }
      }
      return true;
    } else {
      return s.runes.first ^ 0x30 <= 9; /// Here
    }
  }
```
You're taking the first element of the runes from an empty String which leads to an exception.

**Comment by Ephenodrom** [comment]
Hello @modulovalue 

The bug is fixed with version 2.3.5. Already updated it on pub.dev.

It will return false if the given string s is empty.

Regards and thanks for using this package.
