### ISSUE TITLE
Generate selfsigned certificate

### ISSUE THREAD

**Issue by Ephenodrom** [Ephenodrom/Dart-Basic-Utils#55]
It should be possible to generate a self signed certificate using a private key ( RSA/ECC ) and a corresponding CSR.

**Comment by Ephenodrom** [comment]
- id-kp-serverAuth = 1.3.6.1.5.5.7.3.1
- id-kp-clientAuth = 1.3.6.1.5.5.7.3.2
- id-kp-codeSigning = 1.3.6.1.5.5.7.3.3
- id-kp-emailProtection = 1.3.6.1.5.5.7.3.4
- id-kp-timeStamping = 1.3.6.1.5.5.7.3.8
- id-kp-OCSPSigning = 1.3.6.1.5.5.7.3.9

**Comment by gmpassos** [comment]
Add package `coverage` to generate coverage reports.

You can see `shelf_letsencrypt` project as reference:
- https://github.com/gmpassos/shelf_letsencrypt/blob/master/pubspec.yaml
- https://github.com/gmpassos/shelf_letsencrypt/blob/master/run_coverage.sh
- https://github.com/gmpassos/shelf_letsencrypt/blob/master/.github/workflows/dart.yml

**Comment by Ephenodrom** [comment]
@gmpassos Please checkout version 3.8.0 that contains a method to generate a self signed certificate. I testet it with PLESK and it worked fine.
