### ISSUE TITLE
Support for the Key Usage Exension of X.509 certificates

### ISSUE THREAD

**Issue by Nikoo00o** [Ephenodrom/Dart-Basic-Utils#82]
Currently the package only supports the "extended key usage" extension, but not the default "key usage" extension.

**Comment by Nikoo00o** [comment]
Related Pull request: https://github.com/Ephenodrom/Dart-Basic-Utils/pull/81

**Comment by Ephenodrom** [comment]
@Nikoo00o 
Great work. Will be shipped with the next version on pub.dev.

**Comment by Nikoo00o** [comment]
Nice! 
And thanks for the quick response!
