### ISSUE TITLE
 Error: 'RC2Parameters' is imported from both

### ISSUE THREAD

**Issue by raynerhsg** [Ephenodrom/Dart-Basic-Utils#85]
../../../.pub-cache/hosted/pub.dev/basic_utils-5.5.1/lib/src/library/crypto/rc2_engine.dart:4:1: Error: 'RC2Parameters' is imported from both 'package:basic_utils/src/library/crypto/rc2_parameters.dart' and 'package:pointycastle/api.dart'.
import 'package:pointycastle/export.dart';
^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

![image](https://user-images.githubusercontent.com/65260203/225966556-f3dc5b42-06b3-45c7-ba1d-cf95f86afdd9.png)

Error on Android and iOS

**Comment by Ephenodrom** [comment]
Hello I released the pointycastle version 3.7.0 yesterday and i portet some class from this package to pointycastle. I will update basic_utils within the next days.

Take Look at #84.
