### ISSUE TITLE
No algorithm registered of type ECDomainParameters with name: ansip256k1

### ISSUE THREAD

**Issue by WinKoKo91** [Ephenodrom/Dart-Basic-Utils#87]
Hi Sir,

When I try to generate EC PublicKey from bytes I get the following error.

RegistryFactoryException: No algorithm registered of type ECDomainParameters with name: ansip256k1

 `static ECPublicKey loadECPublicKey(var bytes) {`
`    return CryptoUtils.ecPublicKeyFromDerBytes(bytes);`
` }`

kindly check for it.

**Comment by Ephenodrom** [comment]
The curve ansip256k1 is currently not supported by the pointycastle package. Therefore this library does not support ansip256k1 curves too. You can try to open an issue on the pointycastle project to support ansip256k1.

**Comment by Ephenodrom** [comment]
This was a bug in the pointycastle package. There were two OID entries for 1.3.132.0.10. Please update to the latest basic_utils realse 5.5.3.

**Comment by WinKoKo91** [comment]
> This was a bug in the pointycastle package. There were two OID entries for 1.3.132.0.10. Please update to the latest basic_utils realse 5.5.3.

Thank you so much!
