### ISSUE TITLE
nextInt misuse on CryptoUtils

### ISSUE THREAD

**Issue by arkare** [Ephenodrom/Dart-Basic-Utils#89]
https://github.com/Ephenodrom/Dart-Basic-Utils/blob/8b858e37b6b97bf1ec9f3d603cff9a714b5ca3c6/lib/src/CryptoUtils.dart#L257

Max 8-bit unsigned integer is 255 and `nextInt` method is exclusive, the correct usage would be:

```dart
 seeds.add(random.nextInt(255 + 1)); 
```

**Comment by Ephenodrom** [comment]
Looks good, will update a new release on pub.dev within the next 48 hours.
