### ISSUE TITLE
Dart 3 Support

### ISSUE THREAD

**Issue by dukefirehawk** [Ephenodrom/Dart-Basic-Utils#92]
Any plan to upgrade `http` 1.0.0 which requires dart >= 3.0. `mongo_dart` requires this to be upgraded before it can be upgrade.

**Comment by Ephenodrom** [comment]
@dukefirehawk Yes an upgrade to http 1.0.0 is planned. Should be done within the next 1 or 2 days. I will keep you updated.

**Comment by Ephenodrom** [comment]
Version 5.6.0 is available on pub.dev.
